# Generated by Django 4.2.4 on 2023-08-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmenu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmenu',
            name='type',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
