# Generated by Django 4.2.4 on 2023-08-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmenu_app', '0002_taskmenu_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmenu',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
