# Generated by Django 4.2.4 on 2023-08-13 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmenu_app', '0004_alter_taskmenu_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmenu',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskmenu',
            name='is_subtask',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskmenu',
            name='subtasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='taskmenu_app.taskmenu'),
        ),
    ]
