# Generated by Django 4.2.4 on 2023-08-13 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmenu_app', '0005_taskmenu_complete_taskmenu_is_subtask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmenu',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='taskmenu',
            name='is_subtask',
        ),
        migrations.RemoveField(
            model_name='taskmenu',
            name='subtasks',
        ),
    ]
