# Generated by Django 4.2.4 on 2023-08-14 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasklist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('essential', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tasklist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasklist_app.tasklist')),
            ],
        ),
    ]
