# Generated by Django 4.2.4 on 2023-08-13 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_app', '0001_initial'),
        ('tasklist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tasklist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasklist_app.tasklist'),
        ),
    ]
