# Generated by Django 4.2.4 on 2023-08-18 19:21

from django.db import migrations, models
import validator.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, validators=[validator.validator.validate_name])),
                ('mid_init', models.CharField(blank=True, max_length=255, null=True, validators=[validator.validator.validate_name])),
                ('last_name', models.CharField(max_length=255, validators=[validator.validator.validate_name])),
                ('phone', models.CharField(blank=True, max_length=255, null=True, validators=[validator.validator.validate_phone])),
                ('email', models.EmailField(max_length=254)),
                ('notes', models.TextField()),
            ],
        ),
    ]
