# Generated by Django 4.2.4 on 2023-08-16 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_app', '0001_initial'),
        ('contactslist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contactslist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='contactslist_app.contactslist'),
        ),
    ]
