# Generated by Django 4.2.4 on 2023-08-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
