# Generated by Django 4.2.4 on 2023-08-13 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taskmenu_app', '0006_remove_taskmenu_complete_remove_taskmenu_is_subtask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtaskmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='taskmenu_app.taskmenu')),
            ],
        ),
    ]
