# Generated by Django 4.2.4 on 2023-08-28 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taskmenu_app', '0001_initial'),
        ('subtaskmenu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtaskmenu',
            name='connected_task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtask', to='taskmenu_app.taskmenu'),
        ),
        migrations.AddField(
            model_name='subtaskmenu',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='taskmenu_app.taskmenu'),
        ),
    ]
