# Generated by Django 4.2.4 on 2023-08-13 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmenu_app', '0006_remove_taskmenu_complete_remove_taskmenu_is_subtask_and_more'),
        ('subtaskmenu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtaskmenu',
            name='connected_task_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subtask', to='taskmenu_app.taskmenu'),
            preserve_default=False,
        ),
    ]
