# Generated by Django 4.2.4 on 2023-08-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0002_transaction_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
