# Generated by Django 4.2.4 on 2023-08-13 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0001_initial'),
        ('inspector_app', '0001_initial'),
        ('title_app', '0001_initial'),
        ('transaction_app', '0002_transaction_hoa_documents_contingency_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='agent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='agent_app.agent'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pest_inspector_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_inspection_transactions', to='inspector_app.inspector'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='septic_inspector_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='septic_inspection_transactions', to='inspector_app.inspector'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='title_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='title_app.title'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='well_inspector_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='well_inspection_transactions', to='inspector_app.inspector'),
        ),
    ]
