# Generated by Django 4.2.4 on 2023-08-15 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactslist_app', '0001_initial'),
        ('inspector_app', '0002_inspector_contactslist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='contactslist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspectors', to='contactslist_app.contactslist'),
        ),
    ]
