# Generated by Django 4.2.4 on 2023-08-13 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_initial'),
        ('subtask_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='connected_task_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtask', to='task_app.task'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='task_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='task_app.task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtask',
            name='type',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
