# Generated by Django 4.2.4 on 2023-08-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtask_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
